config/routes.rb
Rails.application.routes.draw do

  get "/dashboard" => 'dashboard#index', as: :dashboard

  resources :properties
  devise_for :accounts
  root to: "public#main"

end

app/models/ability.rb
# # frozen_string_literal: true

# class Ability
#   include CanCan::Ability

#   def initialize(account)
#         can :read, properties, public: true

#         return unless account.present?  # additional permissions for logged in users (they can read their own posts)
#         can :read, properties, account: account
#         can [:add_account, :delete], [property]





#     # Define abilities for the user here. For example:
#     #
#     #   return unless user.present?
#     #   can :read, :all
#     #   return unless user.admin?
#     #   can :manage, :all
#     #
#     # The first argument to `can` is the action you are giving the user
#     # permission to do.
#     # If you pass :manage it will apply to every action. Other common actions
#     # here are :read, :create, :update and :destroy.
#     #
#     # The second argument is the resource the user can perform the action on.
#     # If you pass :all it will apply to every resource. Otherwise pass a Ruby
#     # class of the resource.
#     #
#     # The third argument is an optional hash of conditions to further filter the
#     # objects.
#     # For example, here the user can only update published articles.
#     #
#     #   can :update, Article, published: true
#     #
#     # See the wiki for details:
#     # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

#   end
# end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
         #, :confirmable

   has_many :properties

def full_name
  "#{first_name} #{last_name}"
end

def company
  "test company"
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :account

  scope :latest, -> { order created_at: :desc }
  # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/api/v1/postman.rb
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:update, keys: [:first_name, :last_name, :url])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :set_sidebar

  def index
  end

  private

  def set_sidebar
    @show_sidebar = true
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  before_action :set_sidebar, except: [:show]

  # before_action :authenticate_user!, :except => [:index]
  # before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @agent = @property.account
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id
    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    def set_sidebar
      @show_sidebar = true
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bedrooms, :parking_spaces, :photo, :photo_cache)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
    @properties = Property.latest
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper

  def property_thumbnail property
    img = property.photo.present? ? property.photo.thumb.url : "logo.jpg"
    image_tag img, class: "property-thumb"
  end

  def property_photo_url property
    property.photo.present? ? property.photo.url : asset_url("logo.jpg")
  end

end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
<h1 class="h3">Dashboard</h1>
<div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
    </div>
    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
    This week
    </button>
</div>
</div>

<table class="table table-striped table-sm">
    <thead>
    <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        <td>dolor</td>
        <td>sit</td>
    </tr>
    <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
        <td>elit</td>
    </tr>
    <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        <td>odio</td>
        <td>Praesent</td>
    </tr>

    </tbody>
</table>
</div>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container margin: 0rm">
    <p>&copy UrbanFinder 2022</p>
  </footer>

app/views/layouts/_validation.html.erb
<% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrbanFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body id="<%= controller.controller_name %>" class="<%= controller.action_name %> <%= "show-sidebar" if @show_sidebar.present? %>>
    <% if @show_sidebar.nil? %>
    <header>
      <%= render "layouts/nav/public" %>
    </header>
    <%= yield %>

    <% else %>
    <%= render "layouts/nav/dashboard" %>
    <div class="container-fluid">
      <div class="row">
        <%= render "layouts/nav/sidebar" %>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-3">
          <%= yield %>
        </main>
      </div>
    </div>

    <% end %>

<footer>
  <!-- <%= render "layouts/footer" %> -->
</footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    <script>feather.replace()</script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">UrbanFinder</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
      </li>
    </ul>
  </nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">UrbanFinder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if account_signed_in? %>
        <% link_to "Dashboard", dashboard_path, class: "nav-link" %>
        <% else %>
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Latest</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">News</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Advertising</a>
      </li>
      <% if account_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log Out", destroy_account_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log In", new_account_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
      </li>
      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <%= link_to dashboard_path, class: "nav-link" do %>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                Dashboard <span class="sr-only">(current)</span>
                <% end %>

            </li>
            <li class="nav-item">
                <%= link_to properties_path, class: "nav-link" do %>
                <i data-feather="package"></i>
                Properties
                <% end %>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                <i data-feather="calendar"></i>

                Viewings
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="users"></i>
                    Customers
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <i data-feather="bar-chart-2"></i>
                    Reports
                </a>
            </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>Saved reports</span>
        <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
        </a>
        </h6>
        <ul class="nav flex-column mb-2">
        <li class="nav-item">
            <a class="nav-link" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
            Current month
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
            Last quarter
            </a>
        </li>
        </ul>
    </div>
</nav>

app/views/properties/_agent_details.html.erb
<div class="">
    <h3 class="h4"><%= @agent.full_name %></h3>
    <p><%= @agent.company %></p>

    <button class="btn btn-info text-uppercase">Call </button>
    <button class="btn btn-success text-uppercase">Email </button>


</div>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <%= render "layouts/validation", item: @property %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bedrooms %>
    <%= form.number_field :bedrooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :parking_spaces %>
    <%= form.number_field :parking_spaces, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :photo, "Choose Image" %>
    <%= form.file_field :photo, class: "form-control" %>
    <%= form.hidden_field :photo_cache %>

    <% if @property.photo.present? %>
      <%= image_tag @property.photo.thumb.url, class: "mt-4" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit "Upload Property", class: "btn btn-success" %>
  </div>
<% end %>

app/views/properties/_latest_properties.html.erb
<% @properties.each do |property| %>

    <div class="col-4">
        <%= link_to(property_thumbnail(property), property_path(property)) %>
        <h3 class="h5 mt-3"><%= link_to property.name, property_path(property) %></h3>
        <p><%= property.address %></p>
        <div class="amenities">
        <span><i data-feather="users"></i></span>
            <span></span>
            <span></span>

        </div>
    </div>
<% end %>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bedrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: "btn btn-primary" %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class="property-main-photo" style="background-image:url('<%= property_photo_url(@property) %>')">
  <div class="photo-overlay">
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="row">
        <div class="col-6">
          <p class="mb-0"><%= @property.address %></p>
          <p class="h2"><%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "For Sale" %></p>
          </div>
          <div class="col-6 text-center">
            <div class="row mr-3 bg-light p-3">
              <div class="col-4">
                <p class="m-0"><strong>Rooms</strong></p>
                <span class="lead"><%= @property.rooms %></span>
            </div>
            <div class="col-4">
              <p class="m-0"><strong>Bathrooms</strong></p>
              <span class="lead"><%= @property.bedrooms %></span>
          </div>
          <div class="col-4">
            <p class="m-0"><strong>Parking</strong></p>
            <span class="lead"><%= @property.parking_spaces %></span>
          </div>
          </div>
        </div>
        <div class="row border-top border-bottom mt-5 mb-4 pt-4 pb-4">
            <div class="col-6">
              <strong><%= link_to "Est. Monthly Repayments of #{ number_to_currency((@property.price / 360), precision: 0) }", "#", class:"text-success" %></strong>
            </div>
            <div class="col-6 text-right">
              <strong><%= link_to "Can I afford this property?", "#", class:"text-success" %></strong>
            </div>
        </div>


        <div class="row">
          <div class="col">
            <p class="h3">Property Description</p>
    <p>
      <strong>Name:</strong>
      <%= @property.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @property.address %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @property.price %>
    </p>

    <p>
      <strong>Rooms:</strong>
      <%= @property.rooms %>
    </p>

    <p>
      <strong>Bathrooms:</strong>
      <%= @property.bedrooms %>
    </p>
    <!-- <%= link_to 'Edit', edit_property_path(@property), class: "btn btn-success" %> |
    <%= link_to 'Back', properties_path, class: "btn btn-secondary" %> -->

    </div>
  </div>
</div>
</div>
  <div class="col-4">
    <%= render "properties/agent_details" %>
  </div>
</div>
</div>